#! /bin/sh

#bspc monitor DP-4 -d 1 3 5 7 9
#bspc monitor HDMI-0 -d 2 4 6 8 10
bspc monitor DP-4 -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width             3
bspc config window_gap               2
bspc config borderless_monocle       true
bspc config focus_follows_pointer    true
bspc config gapless_monocle          true
bspc config pointer_follows_focus    true
bspc config pointer_follows_monitor  true

sh ~/.config/bspwm/pywal-conf
xsetroot -cursor_name left_ptr

sxhkd -c ~/.config/sxhkd/sxhkdrc &
~/.local/scripts/start_polybar &
